// ==UserScript==
// @ScriptName        墨鱼配置监控
// @Author            tokuwakana
// @Version           V1.0.0
// @UpdateTime        2026-04-29
// @Description       每10分钟检测 ddgksf2013 QuantumultX 配置更新
// ==/UserScript==

[rewrite_local]

[task_local]
*/10 * * * * https://raw.githubusercontent.com/tokuwakana/QX/main/Scripts/ddgksf-monitor.js, tag=墨鱼配置监控, enabled=true

[mitm]
hostname = ddgksf2013.top
